### ISSUE TITLE
Safari not setting cross domain localstorage

### ISSUE THREAD

**Issue by npatelseamless** [ofirdagan/cross-domain-local-storage#10]
So on the Safari v 8.0.2, cross domain local storage doesn't seem to be getting set at all however it's not throwing any errors within the console. No issues from Firefox and Chrome however. Let me know if you have any questions.

Thanks

**Comment by ofirdagan** [comment]
Hi @npatelseamless, I'm OOO this week. I'll get back to you asap.

**Comment by beckelmw** [comment]
Any thoughts on this?

**Comment by ofirdagan** [comment]
Hey, I did manage to reproduce. From some reason Safari doesn't share it's localstorage between tabs. I need to look into it more. If u get any ideas on how to solve it please advice :)

**Comment by manigandham** [comment]
Apple has updated the defaults on Safari 7+ both on desktop and mobile to block 3rd party data. The option is now called "Block cookies and other website data" which refers to things like localstorage which are now completely isolated by domain. 

There are no workarounds anymore (this method was the last one).

**Comment by danamajid** [comment]
Does this mean this way of sharing `localStorage` data is not/will not be possible on Safari?

**Comment by manigandham** [comment]
Outside of using a redirect to set first party cookies, yes.

**Comment by mdaguerre** [comment]
Hey, any update on this? I'm trying to set the xdLocalStorage on safari but isn't working

**Comment by ofirdagan** [comment]
like @manigandham  and @danamajid said. currently it doesn't seems like there's a solution for it.
