### ISSUE TITLE
Problems with getItem

### ISSUE THREAD

**Issue by bernardofire** [ofirdagan/cross-domain-local-storage#12]
I have this code: http://pastebin.com/2NShBRhA
Unfortunately getItem is not working. The url is a local rails application. Could you give me hand ?

**Comment by ofirdagan** [comment]
Hey, Can u give me more details what exactly not working? please try to debug and understand where in the flow you encounter problems

**Comment by bernardofire** [comment]
I'm having problems with the get_key function which uses getItem, it doesnt
get the item, even when it is there. setItem is working fine...

2015-04-26 3:39 GMT-03:00 Ofir Dagan <notifications@github.com>:

> Hey, Can u give me more details what exactly not working? please try to
> debug and understand where in the flow you encounter problems
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ofirdagan/cross-domain-local-storage/issues/12#issuecomment-96331433>
> .
>



-- 
github.com/bernardofire

**Comment by ofirdagan** [comment]
form looking at your code it looks like u will always return undefined for key

the getItem is an async function unlike regualr LocalStorage.. cross domain local storage needs to post a message to an internal iframe which makes it async.. so u should do something like:

```js
function get_key(callback) {
  xdLocalStorage.getItem('cv-collector-id', function(data) { callback(data.value) });
}
```

Then the callback will be called with the value as the param..

hope it helps.

**Comment by bernardofire** [comment]
Solved it using the callbacks! Thanks a lot!
