### ISSUE TITLE
Angular2 version

### ISSUE THREAD

**Issue by no-more** [ofirdagan/cross-domain-local-storage#22]
Hello,

I would like to know if there's any plan for an angular2 version of this component?

Thanks a lot.

**Comment by ofirdagan** [comment]
Hey, unfortunately I currently don't have time to maintain this library. if u want to add support to angular 2 it will be great! I'll be happy to add you as one of this lib contributors if u do.

**Comment by PoppyPham** [comment]
I really hope have a version of this for angular2.

**Comment by LucasBrazi06** [comment]
Did you get it in the end !? :)

**Comment by ofirdagan** [comment]
Sorry.. Unfortunately I don't plan to add angular 2 support. I'll be happy to get PR and merge it in. I guess it'll be for angular 4 now :)

**Comment by LucasBrazi06** [comment]
I'll do my best :)

**Comment by LucasBrazi06** [comment]
Finally, I did it on my own (and simplified it) in angular 4 and used a service that handles both iFrame and standalone acces to local storage.
I can share my work for those that are interested.

**Comment by ofirdagan** [comment]
@LucasBrazi06 - sounds great.. if you'll open source it I'll link to it from the main's repo readme or u can pull request it to here as a new major version with migration readme..

**Comment by erinthon** [comment]
@LucasBrazi06 Hi, you can share with me your code? I'm trying to create one new Angular 4 plugin based on xdLocalStorage.

**Comment by ofirdagan** [comment]
@LucasBrazi06 - I can also give u write permissions to this repo if u want to merge it in.. let me know.

**Comment by kamalakkanni** [comment]
@LucasBrazi06 pls share your code it will be more helpful

**Comment by kiruthika94** [comment]
@LucasBrazi06  Please share your code .
