### ISSUE TITLE
Adding an inter-window communications mechanism

### ISSUE THREAD

**Issue by robertlight** [ofirdagan/cross-domain-local-storage#32]
I think it would be quite easy to add the ability for 2 or more windows who utilize the same cross-domain-local-storage to communicate with each other.   Each window would declare their reference-name to the cross-domain-local-storage package...and each window would addEventListener to a specific message that would come from the iframe.

The iframe (in each window) would monitor the localStorage message queue for messages directed at a particular window and call postMessage to deliver that message.

Do you see any problems with this strategy?   Do you know of any other packages that attempt this kind of functionalty?

**Comment by ofirdagan** [comment]
@robertlight  - that's a great idea. 
I think that it comes to solve somewhat of a different problem (real time communication between cross domain iframe).
I don't know if there are other packages that does that but I'm guessing that there are.

**Comment by robertlight** [comment]
I was thinking of storing arrays in localStorage where we can push and pop messages off the array and then communicate those messages via postMessage to the parent window.

The problem, of course, is that localStorage is not threadsafe across multiple browser windows (or tabs)....so there is a small chance that the array would could be overwritten and a message lost.
