### ISSUE TITLE
NOT work on mobile safari

### ISSUE THREAD

**Issue by hnan** [ofirdagan/cross-domain-local-storage#39]
I tried this nice library, it works in Chrome(Desktop), but not work in mobile safari. Safari has more strict privacy polices that prevent cross site storage sharing. Is it possible to make this library work on mobile safari ?

**Comment by ofirdagan** [comment]
Your'e right. Safari has issues with storing 3rd party cookies in iframes. I don't know how to get over that except introduce a remote storage solution.

**Comment by hnan** [comment]
So with a remote storage solution, how would it work? can you elaborate on that. Thanks.

**Comment by ofirdagan** [comment]
I would use remote storage solution as a fallback.
For example u can use firebase.
So, in case the localstorage doesn't work I would set a cookie (which will identify the client) and according to this cookie (the cookie's value can be a uuid which will be the key) I would save and get the data from firebase.

Of course if you're saving sensitive data, you will need a more secure solution.

**Comment by hnan** [comment]
Hi Ofir, Thanks for the help! That worked out.
